<a href="https://colab.research.google.com/github/Cesarcfw/Colab-Python/blob/main/Pandas_CC_D2_C%C3%A9sarChaves.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulação de dados com PANDAS - Manipulação de dados com lista, tuplas e dicionario

Documentação disponivel: https://pandas.pydata.org/docs/

In [ ]:
import pandas as pd #importa a biblioteca pandas
# criando um Dataframe a partir de uma lista de tuplas:
nomes = ["Vasco", "Claudino", "Clesley"]
idade = [32, 20, 35]
dados = list(zip(nomes, idade))
print(dados)
print()
df = pd.DataFrame(data = dados)
print(df)

[('Vasco', 32), ('Claudino', 20), ('Clesley', 35)]

          0   1
0     Vasco  32
1  Claudino  20
2   Clesley  35

![image.png]()

In [ ]:
import pandas as pd
#Criando um Dataframe a partir de um dicionario:
dados = {"Nome": ["Vasco", "Claudino", "Clesley"],
         "Idade":[32, 20, 35]}
df = pd.DataFrame(data = dados)
print(df)

       Nome  Idade
0     Vasco     32
1  Claudino     20
2   Clesley     35

In [ ]:
import pandas as pd
#Criando DataFrame como modulos personalizados
dados = [("Vasco", 32), ("Claudino", 20), ("Clesley", 35)]
colunas = ["nome", "idade"]
linhas = ["Dublagem", "FalsoPobre", "PrecisaDeAjuda"]
df = pd.DataFrame(data = dados, columns = colunas, index = linhas)
print(df)

                    nome  idade
Dublagem           Vasco     32
FalsoPobre      Claudino     20
PrecisaDeAjuda   Clesley     35

In [ ]:
import pandas as pd
#Modificando codigos
dados = [("Vasco", 32), ("Claudino", 20), ("Clesley", 35)]
colunas = ["nome", "idade"]
linhas = ["Dublagem", "FalsoPobre", "PrecisaDeAjuda"]
df = pd.DataFrame(data = dados, columns = colunas, index = linhas)
df.columns = ["Pessoas", "Devendo"]
df.index = ["Frio", "Banana", "Kpoper"]
print(df)

print(list(df.index))
print(list(df.columns))
print(df.ndim)
print(df.shape)
print(df.size)
print(df.empty)

         Pessoas  Devendo
Frio       Vasco       32
Banana  Claudino       20
Kpoper   Clesley       35
['Frio', 'Banana', 'Kpoper']
['Pessoas', 'Devendo']
2
(3, 2)
6
False

# Desafio
proposta 4: Dados de musicas de uma plataforma de streaming
* a) Mais ouvidas
* b) Artista com mais musicas
* c) Gênero mais popular
* d) Musica mais recente
* e) Adicionar uma nova coluna com a duração em segundos

In [ ]:
# Proposta de exercício de Data Frame: Dados de músicas de uma plataforma de streaming
import pandas as pd

nome_musicas = ["Blinding Lights", "Cruel Summer", "One Dance", "This Is What You Came For", "Sea Of Problems"]
artistas = ["The Weekend", "Taylor Swift", "Drake", "Rihanna", "Glichery"]
genero = ["R&B", "electropop", "HipHop", "House", "Phonk"]
ano_lancamento = [2020, 2019, 2016, 2016, 2023]
duracao_musica = [3.2, 3.0, 4.4, 3.5, 1.5]

dados_musicais = {
    'Música': nome_musicas,
    'Artista': artistas,
    'Gênero': genero,
    'Ano de lançamento': ano_lancamento,
    'Duração (segundos)' : duracao_musica,
}

music_df = pd.DataFrame(dados_musicais)
print(music_df)

# a) Mais ouvidas
print("a) Mais ouvidas: ")
mais_ouvida = music_df.loc[music_df['Ano de lançamento'].idxmax()]['Música']
print(mais_ouvida)
print()
# b) Artista com mais músicas
print("b) Artistas com mais músicas:")
artista_mais_musicas = music_df['Artista'].mode()[0]
print(artista_mais_musicas)
print()
# c) Gênero mais ouvido
print("c) Gênero mais popular:")
genero_mais_popular = music_df['Gênero'].mode()[0]
print(genero_mais_popular)
print()
# d) Música mais recente
print("d) Música mais recente:")
musica_mais_recente = music_df.loc[music_df['Ano de lançamento'].idxmax()]['Música']
print(musica_mais_recente)
print()
# e) Adicionar nova coluna com duração de segundos
print("e) Duração (segundos):")
music_df['Duração (segundos)'] = music_df['Duração (segundos)'] * 60
print(music_df)
print()
display(music_df)

                      Música       Artista      Gênero  Ano de lançamento  \
0            Blinding Lights   The Weekend         R&B               2020
1               Cruel Summer  Taylor Swift  electropop               2019
2                  One Dance         Drake      HipHop               2016
3  This Is What You Came For       Rihanna       House               2016
4            Sea Of Problems      Glichery       Phonk               2023

   Duração (segundos)
0                 3.2
1                 3.0
2                 4.4
3                 3.5
4                 1.5
a) Mais ouvidas:
Sea Of Problems

b) Artistas com mais músicas:
Drake

c) Gênero mais popular:
HipHop

d) Música mais recente:
Sea Of Problems

e) Duração (segundos):
                      Música       Artista      Gênero  Ano de lançamento  \
0            Blinding Lights   The Weekend         R&B               2020
1               Cruel Summer  Taylor Swift  electropop               2019
2                  One Dance         Drake      HipHop               2016
3  This Is What You Came For       Rihanna       House               2016
4            Sea Of Problems      Glichery       Phonk               2023

   Duração (segundos)
0               192.0
1               180.0
2               264.0
3               210.0
4                90.0

,Música,Artista,Gênero,Ano de lançamento,Duração (segundos)
0,Blinding Lights,The Weekend,R&B,2020,192.0
1,Cruel Summer,Taylor Swift,electropop,2019,180.0
2,One Dance,Drake,HipHop,2016,264.0
3,This Is What You Came For,Rihanna,House,2016,210.0
4,Sea Of Problems,Glichery,Phonk,2023,90.0

Proposta 2: Dados de Estudantes de uma Escola

* a) Média de Notas
* b) Aluno com maior nota em Estrutura de Dados
* c) Aluno mais novo
* d) Aluno com menor nota em Banco de Dados
* e) Adicionar uma nova coluna com a média geral das notas import pandas as pd

In [ ]:
aluno = ["Amanda", "Vitu", "Vasco", "César", "Breno"]
notaEd1 = [9, 7, 10, 8, 6]
notaEd2 = [10, 9, 9, 10, 8]
notaBd1 = [8, 5, 3, 6, 7]
notaBd2 = [9, 9, 8, 9, 8]
data_nasc_aluno = [2003, 2006, 1999, 2004, 2001]

dados_alunos = {
    'Alunos' : aluno,
    'Nota ED 1' : notaEd1,
    'Nota ED 2' : notaEd2,
    'Nota BD 1' : notaBd1,
    'Nota BD 2' : notaBd2,
    'Idade' : data_nasc_aluno,
}

estudantes = pd.DataFrame(dados_alunos)
print(estudantes)
print()

#a) Média de Notas
print("a) Média de notas de Estrutura de Dados: ")
media_notas = (estudantes['Nota ED 1'] + estudantes['Nota ED 2']) / 2
print(media_notas)
print()
print("Média de notas de Banco de Dados: ")
media_notas = (estudantes['Nota BD 1'] + estudantes['Nota BD 2']) / 2
print(media_notas)
print()

#b) Aluno com maior nota em Estrutura de Dados
print("b) Aluno com maior nota em Estrutura de Dados: ")
estudantes['Média ED'] = (estudantes['Nota ED 1'] + estudantes['Nota ED 2']) / 2
aluno_maior_nota_ed = estudantes.loc[estudantes['Média ED'].idxmax()]['Alunos']
print(aluno_maior_nota_ed)
print()
print("Aluno com maior nota em Banco de Dados: ")
estudantes['Média BD'] = (estudantes['Nota BD 1'] + estudantes['Nota BD 2']) / 2
aluno_maior_nota_bd = estudantes.loc[estudantes['Média BD'].idxmax()]['Alunos']
print(aluno_maior_nota_bd)
print()

#c) Aluno mais novo
print("c) Aluno mais novo: ")
aluno_mais_novo = estudantes.loc[estudantes['Idade'].idxmax()]['Alunos']
print(aluno_mais_novo)
print()

#d) Aluno com menor nota em Banco de Dados
print("d) Aluno com menor nota em Banco de Dados: ")
estudantes['Média BD'] = (estudantes['Nota BD 1'] + estudantes['Nota BD 2']) / 2
aluno_menor_nota_bd = estudantes.loc[estudantes['Média BD'].idxmin()]['Alunos']
print(aluno_menor_nota_bd)
print()

#e) Adicionar uma nova coluna com a média geral das notas import pandas as pd
print("e) Adicionar uma nova coluna com a média geral das notas: ")
estudantes['Média Geral'] = (estudantes['Nota ED 1'] + estudantes['Nota ED 2'] + estudantes['Nota BD 1'] + estudantes['Nota BD 2']) / 4
print(estudantes)
print()
display(estudantes)

   Alunos  Nota ED 1  Nota ED 2  Nota BD 1  Nota BD 2  Idade
0  Amanda          9         10          8          9   2003
1    Vitu          7          9          5          9   2006
2   Vasco         10          9          3          8   1999
3   César          8         10          6          9   2004
4   Breno          6          8          7          8   2001

a) Média de notas de Estrutura de Dados:
0    9.5
1    8.0
2    9.5
3    9.0
4    7.0
dtype: float64

Média de notas de Banco de Dados:
0    8.5
1    7.0
2    5.5
3    7.5
4    7.5
dtype: float64

b) Aluno com maior nota em Estrutura de Dados:
Amanda

Aluno com maior nota em Banco de Dados:
Amanda

c) Aluno mais novo:
Vitu

d) Aluno com menor nota em Banco de Dados:
Vasco

e) Adicionar uma nova coluna com a média geral das notas:
   Alunos  Nota ED 1  Nota ED 2  Nota BD 1  Nota BD 2  Idade  Média ED  \
0  Amanda          9         10          8          9   2003       9.5
1    Vitu          7          9          5          9   2006       8.0
2   Vasco         10          9          3          8   1999       9.5
3   César          8         10          6          9   2004       9.0
4   Breno          6          8          7          8   2001       7.0

   Média BD  Média Geral
0       8.5         9.00
1       7.0         7.50
2       5.5         7.50
3       7.5         8.25
4       7.5         7.25

,Alunos,Nota ED 1,Nota ED 2,Nota BD 1,Nota BD 2,Idade,Média ED,Média BD,Média Geral
0,Amanda,9,10,8,9,2003,9.5,8.5,9.00
1,Vitu,7,9,5,9,2006,8.0,7.0,7.50
2,Vasco,10,9,3,8,1999,9.5,5.5,7.50
3,César,8,10,6,9,2004,9.0,7.5,8.25
4,Breno,6,8,7,8,2001,7.0,7.5,7.25

# Provinha
03/05/2024

* Criar um DataFrame
* Responder as cinco perguntas relacionadaos ao DataFrame
* Gerar a tabela do DataFrame

César Chaves, Matheus Brandão, Gabriel Azevedo

In [ ]:
aluno = ["Gabriel Mateus", "Jorge", "Roberto Jeferson"]
notaAT = [5, 10, 1]
notaA1 = [9, 10, 1]
notaA2 = [4, 9.5, 3.5]
data_nasc_aluno = [2001, 2008, 1998]

dados_alunos = {
    'Alunos' : aluno,
    'Nota Atividades' : notaAT,
    'Nota Avaliação 1' : notaA1,
    'Nota Avaliação 2' : notaA2,
    'Idade' : data_nasc_aluno,
}

colegio_deus_me_livre = pd.DataFrame(dados_alunos)
display(colegio_deus_me_livre)
print()

,Alunos,Nota Atividades,Nota Avaliação 1,Nota Avaliação 2,Idade
0,Gabriel Mateus,5,9,4.0,2001
1,Jorge,10,10,9.5,2008
2,Roberto Jeferson,1,1,3.5,1998

Perguntas
* Quantas colunas os DataFrame possui
* Qual é o nome da segunda pessoa na lista
* qual é a media das notas
* qual é a idade do quarto individuo na lista
* Adicione uma nova pessoa ao DataFrame
* Remova a terceira pessoa ao DataFrame

In [ ]:
# a) Quantas colunas os DataFrame possui
print(colegio_deus_me_livre.shape)

(3, 5)

In [ ]:
# b) Qual é o nome da segunda pessoa na lista
print(colegio_deus_me_livre.iloc[1][0])

Jorge

In [ ]:
# d) Adicione uma nova pessoa ao DataFrame
colegio_deus_me_livre.loc[len(colegio_deus_me_livre)]=["Claudio Arraio", 10, 5, 8, 2004]
print(colegio_deus_me_livre)

             Alunos  Nota Atividades  Nota Avaliação 1  Nota Avaliação 2  \
0    Gabriel Mateus                5                 9               4.0
1             Jorge               10                10               9.5
2  Roberto Jeferson                1                 1               3.5
3    Claudio Arraio               10                 5               8.0

   Idade
0   2001
1   2008
2   1998
3   2004

In [ ]:
# c) Qual é a media das notas
print("a Média de notas dos alunos")
media_notas = (colegio_deus_me_livre['Nota Atividades'] + colegio_deus_me_livre['Nota Avaliação 1'] + colegio_deus_me_livre['Nota Avaliação 2']) / 3
print(media_notas)

a Média de notas dos alunos
0    6.000000
1    9.833333
2    1.833333
3    7.666667
dtype: float64

In [ ]:
# e) Qual é a idade do quarto individuo na lista
anos = (2024 - colegio_deus_me_livre.iloc[3][4])
print(anos)

20

In [ ]:
# f) Remova a terceira pessoa ao DataFrame
colegio_deus_me_livre.drop([2])

           Alunos  Nota Atividades  Nota Avaliação 1  Nota Avaliação 2  Idade
0  Gabriel Mateus                5                 9               4.0   2001
1           Jorge               10                10               9.5   2008
3  Claudio Arraio               10                 5               8.0   2004

In [ ]:
display(colegio_deus_me_livre)
print()
print("Solução dos desafios:")
print()
print("O Data frame possui",colegio_deus_me_livre.shape[1],"colunas.")
print()
print("O nome da segunda pessoa da lista é:", colegio_deus_me_livre.iloc[1]['Alunos'])
print()
print("A media das notas é: \n", media_notas)
print()
print("A idade do quarto individuo é:", anos)
print()
print("A nova pessoa se chama", colegio_deus_me_livre.iloc[3]['Alunos'])
print()
print("O reprovado ja foi deletado")
print()

,Alunos,Nota Atividades,Nota Avaliação 1,Nota Avaliação 2,Idade
0,Gabriel Mateus,5,9,4.0,2001
1,Jorge,10,10,9.5,2008
2,Roberto Jeferson,1,1,3.5,1998
3,Claudio Arraio,10,5,8.0,2004

Solução dos desafios:

O Data frame possui 5 colunas.

O nome da segunda pessoa da lista é: Jorge

A media das notas é:
 0    6.000000
1    9.833333
2    1.833333
3    7.666667
dtype: float64

A idade do quarto individuo é: 20

A nova pessoa se chama Claudio Arraio

O reprovado ja foi deletado